version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
